### ISSUE TITLE
ImportError when running manage.py migrate without any_urlfield

### ISSUE THREAD

**Issue by cosmicyom** [edoburu/django-fluent-contents#42]
When I run `manage.py migrate picture` I get this error : 

    ImportError: No module named 'any_urlfield'

`fluent_contents.plugins.picture` is in my INSTALLED_APPS but I didn't installed the `django-any-urlfield` package. Migrations souldn't import `any_urlfield` ...

I had to delete the file `plugins/picture/migrations/0001_initial.py` to fix it.

**Comment by vdboor** [comment]
Thanks for reporting this! This is now fixed in v1.0.1!

The migrations no longer directly link to the AnyUrlField, but link to it's wrapper instead. You can now use those extra packages optionally, as they were intended to be.
