### ISSUE TITLE
Initial migration fails for sharedcontent plugin

### ISSUE THREAD

**Issue by barryrowlingson** [edoburu/django-fluent-contents#47]
In a new virtualenv:

     pip install Django==1.7.8
     mkdir example.com
     django-admin.py startproject "myexample" "example.com" -e "py,rst,example,gitignore" --template="https://github.com/edoburu/django-project-template/archive/django-fluent.zip"
     cd example.com
     pip install -r requirements.txt

Then I edit settings.py to set the DB to sqlite because I don't have a handy PostgreSQL. Then:

     cd example.com
     python manage.py migrate

does a bunch of init and migrations until it errors with:

    Applying rawhtml.0001_initial... OK
    Applying redirectnode.0001_initial... OK
    Applying sessions.0001_initial... OK
    Applying sharedcontent.0001_initial...Traceback (most recent call last):
    File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
     File "/nobackup/rowlings/Env/fluent/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()

Then more lines of traceback, ending with:

    TypeError: int() argument must be a string or a number, not 'Site'

I don't know if this is because I'm using the sqlite DB backend, or some other problem...

**Comment by bashu** [comment]
comment related line in settings.py and try again

**Comment by barryrowlingson** [comment]
Which related line in settings.py? Do I need to try it with PostgreSQL? I'll see what I can do.

**Comment by barryrowlingson** [comment]
Same error, same place, with a PostgreSQL database.

pip freeze output follows:

Django==1.7.8
Pillow==2.8.2
Pygments==2.0.2
akismet==0.2.0
argparse==1.2.1
blessings==1.6
bpython==0.14.2
curtsies==0.1.19
django-admin-tools==0.5.2
django-any-imagefield==0.8.2
django-any-urlfield==2.1.1
django-appconf==1.0.1
django-axes==1.3.9
django-categories==1.2.3
django-compressor==1.5
django-contrib-comments==1.6.1
django-crispy-forms==1.4.0
django-debugtools==1.3
-e git+https://github.com/smacker/django-filebrowser-no-grappelli.git@25613ff879325f2da8e465c028b9657ae6dd79cf#
egg=django_filebrowser_no_grappelli-master
django-fluent-blogs==1.0
django-fluent-comments==1.0.2
django-fluent-contents==1.0.1
django-fluent-dashboard==0.5
django-fluent-pages==0.9
django-fluent-utils==1.2.1
django-google-tools==1.0.0
django-mptt==0.7.4
django-parler==1.4
-e git+https://github.com/rizumu/django-ping.git@b9e228fe1f338d87b323383509a975fd9df22ef1#egg=django_ping-origi
n/rizumu
django-polymorphic==0.7.1
django-polymorphic-tree==1.1
django-staff-toolbar==1.0
django-tag-parser==2.1
django-taggit==0.14.0
django-taggit-autosuggest==0.2.7
django-template-analyzer==1.5
django-tinymce==1.5.3
django-wysiwyg==0.7.0
future==0.14.3
greenlet==0.4.7
html5lib==1.0b6
micawber==0.3.2
psycopg2==2.6
python-memcached==1.54
pytz==2015.4
raven==5.3.1
requests==2.7.0
six==1.9.0
sorl-thumbnail==12.2
unicode-slugify==0.1.1
wsgiref==0.1.2

**Comment by barryrowlingson** [comment]
I think the function in here:
 fluent_contents/plugins/sharedcontent/utils.py 
is returning a Site object rather than an integer id. If I change the sharedcontent migration to:

('parent_site', models.ForeignKey(default=1, editable=False, to='sites.Site'))

then it seems to work. Suspect the right fix might be to edit utils.py?

**Comment by vdboor** [comment]
This is now fixed in 84bb54cb0ad0ec004a37ebfde4d31c5a9e1fd5a0, you can find django-fluent-contents 1.0.2 on PyPI!
