### ISSUE TITLE
admin.TabularInline support enabled?

### ISSUE THREAD

**Issue by sunjoomoon** [edoburu/django-fluent-contents#70]
For fluent contents plugin, is admin.TabularInline implemented?  For bookmark  example, for 'title, url' model, do admin.TabularInline multiple  bookmark entries and then do 'for' loop in the template. Wondered if this is something implented or if not any work around? or a good time consuming work?

**Comment by vdboor** [comment]
I'm sorry, this is not available. As the plugins are already inlines, this requires "inline-inlines" support. Partial support exists in the feature/inline-mixins branch, but was never completed (and needs to be ported)

**Comment by sunjoomoon** [comment]
Thanks. Well noted.
