### ISSUE TITLE
Saving various PlaceholderFields

### ISSUE THREAD

**Issue by emptyset1** [edoburu/django-fluent-contents#72]
Being a noob here, I've been trying to run your app and example. Even using the unmodified code provided  in the example, I couldn't save more than one ContentItem(s) in a model. Is there some trick to this? How do I save multiple  ContentItem(s)? 

Thank you, I would really appreciate your answer.

**Comment by vdboor** [comment]
I've just double checked the example project, and I've been able to create multiple items at the same page. (by pressing the Add button multiple times). What browser or system are you using, and do you see any errors in the browser/console?

**Comment by emptyset1** [comment]
Sorry for writing back so late. It was an installation issue. Works fine now. You can close this issue.
