### ISSUE TITLE
More than one plugin_pool

### ISSUE THREAD

**Issue by emptyset1** [edoburu/django-fluent-contents#77]
Hi there,

Would it be at all possible to have two or more sets of plugins? Say, I would like to have two completely different types of content for different apps. If so, how do I go about it?

Thank you very much.

Also, thanks a lot for the package. It's great.

**Comment by vdboor** [comment]
I'm not sure what you're looking for with 2 pools. Instead, I think you want to limit the displayed plugins using `FLUENT_CONTENTS_PLACEHOLDER_CONFIG`
